version: "3.8"

services:
  log-reader:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: test-log-reader

    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
